Solution
aleksandr-hrankin/internet-shop pull request #1
Opened 2020-09-02 14:51 UTC by aleksandr-hrankin

2020-09-02 14:57 UTC, andromash commented on .idea/vcs.xml
> +</project>
This file is from .idea. You should have included this folder to gitignore

2020-09-02 15:09 UTC, aleksandr-hrankin commented on .idea/vcs.xml
> +</project>
автогенератор gitignore подкачал

2020-09-02 15:56 UTC, andromash approved these changes

2020-09-03 07:18 UTC, KseniiaMakarova requested changes

2020-09-03 07:18 UTC, KseniiaMakarova commented on .gitignore
> +.idea/*
это так не сработает

у тебя в master сейчас уже запушена папка .idea и файл с расширением .iml
нужно убрать их отдельно из мастера, отдельно из этого ПР
https://youtu.be/b2Qlqva4-H4 - инструкция

2020-09-03 07:18 UTC, KseniiaMakarova commented on .idea/vcs.xml
> +</project>
don't use autogenerator please

2020-09-03 07:18 UTC, KseniiaMakarova commented on pom.xml
> +
you have already pushed pom.xml to master

2020-09-03 07:18 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/model/ShoppingCart.java
> +    }
you will not receive products list from outside

2020-09-03 07:18 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/model/Order.java
> +    }
same here

2020-09-03 07:18 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +                .filter(x -> Objects.equals(x.getId(), id))
let's not use class Objects

2020-09-03 07:18 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +        return Storage.products.removeIf(x -> x.getId().equals(id));
`x` is not informative

2020-09-03 07:18 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/Application.java
> +        xbox360.setId(2L);
why are you setting the id?

2020-09-03 07:18 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/Application.java
> +        productService.delete(1L);
```suggestion
        productService.delete(iPhone.getId());
```

2020-09-03 07:18 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/Application.java
> +        System.out.println(productService.get(2L));
same here, don't use hardcoded id, get it from the product you wish with a getter

2020-09-03 08:08 UTC, aleksandr-hrankin commented on .idea/vcs.xml
> +</project>
okey

2020-10-16 07:42 UTC, closed without merging