Added orders
aleksandr-hrankin/internet-shop pull request #6
Opened 2020-09-10 16:44 UTC by aleksandr-hrankin

2020-09-10 16:49 UTC, DariaPikul requested changes
What about All Products - Admin page?

2020-09-10 16:49 UTC, DariaPikul commented on src/main/java/com/internet/shop/controller/order/CompleteOrderController.java
> +        resp.sendRedirect(req.getContextPath() + "/user/orders");
Don't you clear it at the service layer in the orderService.complete() method? 
Same about id setting

2020-09-11 07:21 UTC, DariaPikul approved these changes

2020-09-11 08:18 UTC, Sofasmile approved these changes
GetAllProductsFromStorage - краще перейменувати на більш зрозуміле. Щось пов'язане з адміном, чи з управлінням продуктами

2020-09-13 14:35 UTC, merged